# Contract Addresses
pools:
  - address: "0000000000000000000000000000000000001017" # ETH-USDST pool
  - address: "000000000000000000000000000000000000101b" # GOLDST-USDST pool
  - address: "000000000000000000000000000000000000101d" # SILVST-USDST pool
  # Stable Pools
  - address: "bab35f9fe024e2735edae7a9c0aba4db260a649c" # sUSDS-USDST pool
  - address: "5888fbe6d6774c1d5788a7b631fc2a2fe88c44c6" # syrupUSDC-USDST pool
  - address: "3d1dc151402858521bf9beaa8c72a68c9b4fc2fe" # USDT-USDC-USDST pool

# Trading Parameters
trading:
  fee_bps: 30 # Pool fee in basis points (0.3%)
  min_profit: 0.01 
  slippage_factor_amm: 0.96 # 4% slippage tolerance for AMM pools
  slippage_factor_stable: 0.92 # 8% slippage tolerance for stable pools

# Oracle Configuration
oracle:
  timeout: 10 # API request timeout in seconds
  blockapps_price_oracle: "0000000000000000000000000000000000001002" # BlockApps on-chain price oracle address

# CDP Liquidation Settings
liquidation:
  enabled: true

# Health Check
health_port: 3010

# Execution Settings
execution:
  execution_interval: 300 # seconds between scans
  vault_addr: "34bc729f66106a146b0864e673a3571b28fa23e1" # this is mainnet vault address
